---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  media-zfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 116Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: media-zfs-pvc # name of pvc which can claim this PV
    namespace: media # namespace for the pvc
  # csi:
  #   driver: zfs.csi.openebs.io
  #   fsType: zfs
  #   volumeAttributes:
  #     openebs.io/poolname: tank
  #   volumeHandle: media
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: openebs.io/nodeid
  #             operator: In
  #             values:
  #               - control-01
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
  mountOptions:
    - hard
    - noatime
    - nconnect=16
    - nfsvers=4.2
  nfs:
    path: /
    server: 192.168.2.30