apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: kube-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 3m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      allowSnippetAnnotations: true
      nodeSelector:
        kubernetes.io/hostname: control-01
      extraEnvs:
        - name: TZ
          value: "${TZ}"
      service:
        # annotations:
        #   metallb.universe.tf/address-pool: "control-ips"
        #   metallb.universe.tf/loadBalancerIPs: "192.168.2.30"
        enabled: true
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      #electionID: ingress-controller-leader
      # ingressClass: external
      # ingressClassByName: true
      ingressClassResource:
        name: external
        enabled: true
        default: true
      #   controllerValue: "k8s.io/ingress-nginx-external"
      # admissionWebhooks:
        # objectSelector:
          # matchExpressions:
            # - key: ingress-class
              # operator: In
              # values:
                # - external
      config:
        use-gzip: true
        enable-brotli: true
        #enable-ocsp: true
        #enable-real-ip: true
        hsts-max-age: 31449600
        proxy-buffer-size: 16k
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        proxy-buffering: "off"
        #use-proxy-protocol: true
        http-redirect-code: "308"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: true
        force-ssl-redirect: true
      metrics:
        enabled: true
        # serviceMonitor:
        #   enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      extraArgs:
        default-ssl-certificate: "cert-manager/cloudflare-tls"
      #  enable-ssl-passthrough: true
      #topologySpreadConstraints:
      #  - maxSkew: 2
      #    topologyKey: kubernetes.io/hostname
      #    whenUnsatisfiable: DoNotSchedule
      #    labelSelector:
      #      matchLabels:
      #        app.kubernetes.io/instance: ingress-nginx
      #tolerations:
      #  - effect: NoSchedule
      #    operator: Exists
      #  - effect: NoExecute
      #    operator: Exists
      resources:
        requests:
          memory: 300Mi
          cpu: 100m
        limits:
          cpu: 300m
          memory: 900Mi
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 3.8.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
      resources:
        requests:
          memory: 75Mi
          cpu: 50m
        limits:
          cpu: 50m
          memory: 75Mi
