---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # - ./media-pv.yaml
  # - ./media-zfs-pvc.yaml
  # Flux-Kustomizations
  - ./ersatz/ks.yaml
  # - ./homarr/ks.yaml
  # - ./jellyfin/ks.yaml
  - ./kavita/ks.yaml
  # - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  # - ./sabnzbd/ks.yaml
  # - ./sonarr/ks.yaml
  # - ./prowlarr/ks.yaml
  # - ./ombi/ks.yaml
  - ./cwa/ks.yaml
  - ./emby/ks.yaml
  - ./media-storage/ks.yaml
  - ./booklore/ks.yaml