apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: renovate
  name: renovate
  namespace: renovate
spec:
  template:
    metadata:
      labels:
        app: renovate
    spec:
      containers:
        - image: ghcr.io/mend/renovate-ce:13.1.0
          imagePullPolicy: Always
          name: renovate
          env:
          - name: MEND_RNV_DATA_HANDLER_TYPE
            value: postgresql
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: renovate-user-password
                key: password
          - name: PGDATABASE
            value: renovate
          - name: PGUSER
            value: renovate
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: cnpg-renovate-rw.cnpg-system.svc.cluster.local
          - name: MEND_RNV_PLATFORM
            value: github
          - name: MEND_RNV_GITHUB_APP_KEY
            valueFrom:
              secretKeyRef:
                name: renovate-github-key
                key: private-key
          - name: MEND_RNV_GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                name: renovate-github-secret
                key: app-id
          - name: MEND_RNV_ACCEPT_TOS
            value: "y"
          - name: MEND_RNV_LICENSE_KEY
            value: "eyJsaW1pdCI6IjEwIn0=.30440220457941b71ea8eb345c729031718b692169f0ce2cf020095fd328812f4d7d5bc1022022648d1a29e71d486f89f27bdc8754dfd6df0ddda64a23155000a61a105da2a1"
          ports:
          - name: renovate
            containerPort: 8080
            protocol: TCP
          volumeMounts:
          - name: renovate-config
            mountPath: /config
          resources:
            requests:
              memory: 275Mi
              cpu: 75m
            limits:
              memory: 450Mi
              cpu: 300m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: renovate-config
        persistentVolumeClaim:
          claimName: "renovate-config"
  selector:
    matchLabels:
      app: renovate