apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwa-library-pvc
  namespace: media
  labels:
    app: cwa
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: ceph-block
  