---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app media-storage
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/media/media-storage/volumes
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 3m
  retryInterval: 1m
  timeout: 2m
  dependsOn:
    - name: nfs