apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  namespace: media
  labels:
    app: emby
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 150G
  storageClassName: ceph-block
  