apiVersion: v1
kind: Service
metadata:
  name: booklore-service
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: booklore
  ports:
     # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6060
      protocol: TCP
      targetPort: 6060
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 31400
