apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: biggs.dog
spec:
  ingressClassName: external
  rules:
  - host: booklore.biggs.dog
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: booklore-service
            port:
              number: 6060