---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nfd/ks.yaml
  - ./nfs/ks.yaml
  # - ./zfs/ks.yaml
  - ./intel-gpu-plugin/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
  - ./cilium/ks.yaml